CREATE TABLE PLAYLIST (
  id serial PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  description VARCHAR DEFAULT '',
  createTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  channelId INTEGER NOT NULL,
  FOREIGN KEY (channelId) REFERENCES channel(id) ON DELETE CASCADE
);
