CREATE TABLE CHANNEL (
  id serial PRIMARY KEY,
  title VARCHAR(128) NOT NULL UNIQUE,
  description VARCHAR DEFAULT '',
  subscribersCount INTEGER DEFAULT 0,
  createTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userId INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
