CREATE TABLE SUBSCRIBER (
  id serial PRIMARY KEY,
  userId INTEGER NOT NULL,
  channelId INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (channelId) REFERENCES CHANNEL(id) ON DELETE CASCADE
);
