host: localhost
port: 8080
db:
  host: localhost
  port: 5436
  username: postgres
  dbname: go_video_hosting
  sslmode: disable
mail:
  host: smtp.mail.ru
  port: 25
  from: yo-tube@mail.ru
gRPC:
  host: localhost
  port: 8081
  chunksize: 1024
